name: tf_example
description: "This example demonstrates the usage of the ThirdFactor Flutter library for e-KYC verification in a Flutter application."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  thirdfactor:
    path: ../
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  google_fonts: ^6.1.0
  dart_jsonwebtoken: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
